name: gym_punto_venta
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  shared_preferences: ^2.0.6
  flutter_lints: ^4.0.0
  path_provider: ^2.0.0
  file_picker: ^5.2.0
  sqflite: ^2.3.3
  path: ^1.9.0
  image_picker: ^1.1.0
  local_auth: ^2.2.0
  device_info_plus: ^10.1.0
  fl_chart: ^0.68.0
  intl: ^0.19.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

platforms:
  macos:
    pluginClass: FilePickerMacOS
  windows:
    pluginClass: FilePickerWindows
  linux:
    pluginClass: FilePickerLinux
