name: gym_punto_venta
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  get: ^4.6.5
  shared_preferences: ^2.0.6
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
