name: gym_punto_venta
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  shared_preferences: ^2.0.6
  flutter_lints: ^4.0.0
  path_provider: ^2.0.0
  file_picker: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

platforms:
  macos:
    pluginClass: FilePickerMacOS
  windows:
    pluginClass: FilePickerWindows
  linux:
    pluginClass: FilePickerLinux
